### ISSUE TITLE
连不上服务器

### ISSUE THREAD

**Issue by YorrickBao** [wangkezun/JadisApp#1]
ip port password 确定是正确的。68元呢 服务器都连不上

**Comment by wangkezun** [comment]
你好。请问一下redis版本号，以及，同网络下。使用redis-cli或者telnet可以连到服务器吗？

**Comment by YorrickBao** [comment]
版本号3.2.8，是外网服务线上在用的，能连，用rdm也能连

**Comment by wangkezun** [comment]
redis是集群还是单点？连不上是点击Test Connection就返回failed吗？

**Comment by YorrickBao** [comment]
是单点。点击test等一段时间才会显示失败。

**Comment by wangkezun** [comment]
怀疑是host或者密码中有特殊字符导致的问题，可以排查一下这个吗？host直接填写ip试一下呢？

**Comment by YorrickBao** [comment]
host是直接写ip的，写http://ip也试过了不行，密码是小写英文没有特殊字符

**Comment by wangkezun** [comment]
应用在连接时会使用redis命令ping尝试连接一次。是不是服务器关掉了ping的响应呢？
我稍后会更新一个版本，将ping命令关掉，并且加入日志系统，/Users/<YOUR USERNAME>/Library/Containers/io.wkz.JadisApp/Data/Library/Logs/Jadis.log 中查找到日志。如果更新后test仍然出错，请附上相关日志。因为目前并没有详细梳理日志，请注意敏感信息泄露。
