### ISSUE TITLE
When i open any base - program crashes

### ISSUE THREAD

**Issue by skoniks** [wangkezun/JadisApp#2]
**Describe the bug**
1. Connect to server
2. Click on any base
3. Program crashes

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5

**Comment by wangkezun** [comment]
sorry for the inconvenience. 
What redis version do you use?
Is redis in standalone mode or cluster mode?
did click server tab show correct info like this 
![image](https://user-images.githubusercontent.com/3012882/59039814-1c2b6500-88a8-11e9-9c78-d7d9089b0c3b.png)

**Comment by skoniks** [comment]
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=76095d16786fbcba
Redis is in standalone mode and there are no data in tab
![image](https://user-images.githubusercontent.com/13507597/59140101-2cc00600-89a2-11e9-8a7f-207e6bee9613.png)

**Comment by wangkezun** [comment]
Found the reason.
It looks like if redis server have password and app config did not set one, when connect to the server,the app will crash.
I will publish an update to fix this issue and you can change your config and add the password.

**Comment by skoniks** [comment]
> Found the reason.
> It looks like if redis server have password and app config did not set one, when connect to the server,the app will crash.
> I will publish an update to fix this issue and you can change your config and add the password.

Oh, u are right! Thanks!
