### ISSUE TITLE
Keys from base are not displayed

### ISSUE THREAD

**Issue by skoniks** [wangkezun/JadisApp#3]
**Describe the bug**
As in the title - keys from any base are not displayed

**To Reproduce**
1. Connecting to redis server (i see the server information and charts)
2. Opening any base (0 / 1 / 2 / ...) and trying to set any test key
3. Updating base - and see nothing, no keys, no data
4. Setting or pushing keys from console and go to step #3

**Desktop (please complete the following information):**
- OS: Mac OS 10.14.5
- Redis server v=4.0.9

**Additional context**
Restarting app don`t help, i notice that adding keys work - but they are not displayed.

![image](https://user-images.githubusercontent.com/13507597/59149813-202fc200-8a23-11e9-9a8b-2ed300b69109.png)
![image](https://user-images.githubusercontent.com/13507597/59149817-2faf0b00-8a23-11e9-8cda-105a73570e0e.png)

**Comment by wangkezun** [comment]
Okay. this because I think use pattern * to display all key by default is a dangerous behavior and may hang the redis server. So you should input your key pattern like "a*" or "*a" (or even "*") to search some keys. Maybe I should add some tips to this.

**Comment by skoniks** [comment]
Oh, its right again. But, i think you really should add tip like a label near pattern field, with info line "type * to list all keys"

**Comment by wangkezun** [comment]
Yeah. Maybe the placeholder in the search box need be more specific. Thanks for your feedback and wish you have a nice day.
